Fix type error in reading data frame
Fixing error: 
```
    row += [str(round(x, 2)) for x in value_list]
                ^^^^^^^^^^^
TypeError: type str doesn't define __round__ method
```